---
root: true

env:
  phantomjs: true
  jasmine: true
  browser: true
  jquery: true
  node: true
  amd: true
  es6: true

globals:
  _: false
  $: false
  app: false
  angular: false
  videojs: false
  grecaptcha: false
  FB: false
  FastClick: false

plugins:
- angular

extends:
- eslint:recommended

rules:
  indent:
  - error
  - 2
  - SwitchCase: 1

  no-func-assign: error

  func-style:
  - error
  - expression
  - allowArrowFunctions: true

  quotes:
  - error
  - single
  - avoidEscape: true
    allowTemplateLiterals: true

  no-magic-numbers:
  - warn
  - ignore:
    - -1
    - 0
    - 1
    detectObjects: true
    ignoreArrayIndexes: true

  no-tabs: error

  space-before-function-paren:
  - error
  - anonymous: never
    named: never
    asyncArrow: ignore

  block-spacing:
  - error
  - always

  array-bracket-spacing:
  - error
  - always
  - singleValue: true
    arraysInArrays: false
    objectsInArrays: false

  comma-spacing:
  - error
  - before: false
    after: true

  func-call-spacing:
  - error
  - never

  key-spacing:
  - error
  - beforeColon: false
    afterColon: true

  keyword-spacing:
  - error
  - before: true
    after: true

  object-curly-spacing:
  - error
  - always

  object-curly-newline:
  - off
  - minProperties: 1

  object-property-newline:
  - warn
  - allowMultiplePropertiesPerLine: true

  space-before-blocks:
  - error
  - always

  space-in-parens:
  - off
  - always
  - exceptions:
    - empty
    - "{}"
    - "[]"
    - "()"

  space-unary-ops:
  - error
  - words: true
    nonwords: false
    overrides:
      typeof: false

  spaced-comment:
  - error
  - always
  - line:
      exceptions:
      - "-"
      - "*"

  no-empty-function:
  - error
  - allow:
    - constructors
    - arrowFunctions

  eqeqeq: error

  no-eq-null: warn

  no-extra-boolean-cast: off

  strict: warn

  wrap-iife: warn

  valid-typeof:
  - error
  - requireStringLiterals: true

  capitalized-comments: off

  linebreak-style:
  - error
  - unix

  eol-last:
  - error
  - always

  comma-dangle:
  - error
  - never

  no-underscore-dangle:
  - error

  no-cond-assign:
  - error
  - always

  no-global-assign:
  - error

  no-extend-native: off

  no-param-reassign:
  - warn
  - props: false

  no-unused-vars:
  - warn
  - vars: all
    args: none

  no-undef: warn

  no-redeclare: off

  no-use-before-define:
  - warn
  - functions: false
    variables: false
    classes: true

  no-trailing-spaces:
  - error
  - skipBlankLines: true

  no-console:
  - error
  - allow:
    - warn
    - error

  camelcase:
  - error
  - properties: always

  curly:
  - error
  - all

  complexity:
  - warn
  - max: 10

  angular/no-private-call:
  - error

  angular/component-limit:
  - error

  angular/di-unused:
  - error

  angular/directive-restrict:
  - error

  angular/di:
  - error
